name: agri
description: "A smart agricultural bot app that leverages Gemini Pro's image recognition and machine learning capabilities, combined with real-time weather data, to provide farmers with crop health diagnostics, predictive insights, and weather-based recommendations."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.2
  dio: ^5.5.0+1
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  uuid: ^4.4.2
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Rubik 
      fonts:
        - asset: assets/fonts/Rubik_Mono_One/RubikMonoOne-Regular.ttf
    - family: Poppins #default font family
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700